language: go

go:
  - 1.4

addons:
  postgresql: "9.4"

before_install:
  - git clone git://github.com/jedisct1/libsodium.git
  - ( cd libsodium; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
  - git clone git://github.com/zeromq/libzmq.git
  - ( cd libzmq; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
  - git clone git://github.com/zeromq/czmq.git
  - ( cd czmq; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
  - go get github.com/smartystreets/goconvey/convey
  - go get github.com/smartystreets/assertions
  - go get golang.org/x/tools/cmd/stringer
  - go get github.com/rickmak/gocyclo
  - go get github.com/oursky/gogocyclo

before_script:
  - psql -c 'CREATE DATABASE ourd_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d ourd_test

script:
  - golint ./...
  - gocyclo -skip-godeps -over 15 . | gogocyclo
  - go generate ./...
  - go test -cover ./...

notifications:
  slack: oursky:PxqsclRADehuWEs51vpgxeUh

