language: go

go:
  - 1.9.4
  - 1.10.2
  - 1.11

addons:
  postgresql: "9.5"

services:
  - redis-server
  - docker

cache:
  directories:
    - $HOME/.cache

go_import_path: github.com/skygeario/skygear-server

before_install:
  - mkdir -p $HOME/.cache/local
  - export LD_INSTALL_PREFIX=$HOME/.cache/local
  - export LD_LIBRARY_PATH=$LD_INSTALL_PREFIX/lib:$LD_LIBRARY_PATH
  - export LIBRARY_PATH=$LD_INSTALL_PREFIX/lib:$LIBRARY_PATH
  - export PKG_CONFIG_PATH=$LD_INSTALL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH
  - mkdir -p $LD_INSTALL_PREFIX/src
  - pushd $LD_INSTALL_PREFIX/src
  - $TRAVIS_BUILD_DIR/scripts/build-git-lib.sh git://github.com/jedisct1/libsodium.git 1.0.8
  - $TRAVIS_BUILD_DIR/scripts/build-git-lib.sh git://github.com/zeromq/zeromq4-1.git v4.1.4
  - popd
  - sudo curl -fsSL -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
  - sudo curl -fsSL -o /usr/local/bin/vg https://github.com/GetStream/vg/releases/download/v0.8.0/vg-linux-amd64
  - curl -fsSL https://github.com/alecthomas/gometalinter/releases/download/v2.0.11/gometalinter-2.0.11-linux-amd64.tar.gz | sudo tar --strip-components 1 -C /usr/local/bin -zx
  - sudo chmod +x /usr/local/bin/dep /usr/local/bin/vg
  - 'eval "$(vg eval --shell bash)"'
  - vg init

install:
  - sudo apt-get install -y postgresql-9.5-postgis-2.3
  - vg ensure

before_script:
  - psql -c 'CREATE DATABASE skygear_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d skygear_test

script:
  - WITH_ZMQ=1 make generate
  - git status | grep "_gen.go$"; test $? -eq 1
  - git status | grep "_string.go$"; test $? -eq 1
  - git status | grep "mockgen.*go$"; test $? -eq 1
  - WITH_ZMQ=1 make lint
  - WITH_ZMQ=1 make test

jobs:
  allow_failures:
    - name: legacy
  include:
    - name: legacy
      script:
      - WITH_ZMQ=1 make generate
      - WITH_ZMQ=1 make test GO_TEST_PACKAGE=./pkg/server/...

before_deploy:
  - if [[ ! -z "$TRAVIS_TAG" ]]; then make all archive; fi

deploy:
  - provider: releases
    api-key: "$GITHUB_RELEASE_TOKEN"
    file:
      - "dist/skygear-server-*.tar.gz"
      - "dist/skygear-server-*.zip"
    skip_cleanup: true
    file_glob: true
    on:
      repo: SkygearIO/skygear-server
      tags: true
      go: 1.9.4
  - provider: script
    script: ./scripts/deploy-docker-hub.sh
    skip_cleanup: true
    on:
      repo: SkygearIO/skygear-server
      all_branches: true
      go: 1.9.4
  - provider: script
    script: ./scripts/deploy-quay-io.sh
    skip_cleanup: true
    on:
      repo: SkygearIO/skygear-server
      all_branches: true
      go: 1.9.4

notifications:
  slack:
    secure: "dza31bqJ4z51o2x4A0fowKxR6Brop/whekwIZ+JLfjBxZrIyYN0QxnHdi2kcEJwWFPtZdoenCRCLsCATB6/fkHieYkNrEpRjGkzVfOmtH7nYgC+870JH9gHGoWPkL1iTJ69Cl7cqBRXcR5Pr+wfl+RK+GdZnfKjyZTcr/dj1IS41sSCgGONhFmqMiwiJAlbvPIxOE4bbxJmnwHj71drWihLk7rweP0bqmq92/4fK0u/3to1Ng4X71ImSSqdbj+jyX9mNiMhkkPWdBupUOyMARcKo0B5jUwVy7GwlG68b8BoOkFwi4zNaQ44metHXt8EkMWGvaXYvSlnkzqDiT5ZlWBt5ZIruB4RmpGcMxTEAgM0LbJ5bm8Rp8D7K3NNTPNp6S/QS5bmpFIoRv8qXhbWaJ4qzmAOMQIIOzBRDXKWfaUNd5XHlvcIyyD7zLWJJRO4Sy+S5IjzBBRPJNW5XAB3MNt9FZt2DL/NK0u6uUEQsfoezuYq5BcWJ+1IJY/48UIL0z675jTHRiqAejrqorpneYHVPRRUh2fZf0HeW9tpheFFt1D77/dICvnvd7CWLdKaH7wRpicnKozegGGqthyTJs/iTAXbcIbYeBC1fA0/HOnSV7daPkrXcYHBuQqYOnfQae4KvkRc1tlQStEZz8qkMqaU4mBwihEjGky9wA19L/Mk="

env:
  global:
    # GITHUB_RELEASE_TOKEN
    - secure: "ZYxuSD05SgXD3oyzmOOw+o0QpQeG76yoOknP/bSh2uqGgf27qHy+gxvUqBXuJIKVZiKSlfSEO07XMGI5Jl9SqfqumFVdyh5jI2pKN+pZ5yuDokiJagb57jrM/CRaJj0df7qrBa21PGxXDQ52htv1GKGHSDifaXoOdAk9Uetp734RFBWsHXDNSN/RISuedVE5v5d05tB+CqqTAc3pjteDZhfFU5Z89yWaUtMBaGEW8++1Wd2kkMdrPm18dZ4Ylta/VVlxyDY8vtVJUOpXyeLTNAEMB/YsqP3Uauc46ynxbfqZLty4H+3pP24jgBuEQuxCeTcc8HDfi+5twVJtZ/1Xp+7GrD/6CjPnaLqafW6lDD06n62HOgI2/fxWWCKvQslKmpmxUQDDWtsQzS/YzncoN+RekHx1FZ8Nl+NRB5lSuUTtc96dUQD/lC5bl1mjMZS28G6yTtUodDnRBprjyI5vCzqQjE+gutzuMPGgom3NGqRRfNIXPmhyvhBpLbNdrxALSYf8F27PZ8dWxBUk95w/1HnfeEkTGZyWE1MkpKi9lKtsLHd4KTbqu6jRoVfPayJyj3FlddK6Lb0GM3OXuw9yb2kO60ZEvs4jLRzGAURnFVZCgUZgR+SfEB1Txn+X/0T1iFEzUKr3UpuU/c4onJLAf/xhkOsRr9BtsC5KE7pGz0M="
