language: go

go:
  - 1.4
  - tip

before_install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/golang/lint/golint

script:
  - golint ./...
  - go test -cover ./...

notifications:
  slack: oursky:PxqsclRADehuWEs51vpgxeUh
