language: go

go:
  - 1.4
  - tip

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
  - go get github.com/smartystreets/goconvey/convey
  - go get github.com/smartystreets/assertions

script:
  - golint ./...
  - go test -cover ./...

notifications:
  slack: oursky:PxqsclRADehuWEs51vpgxeUh
