language: go

sudo: false

go:
  - 1.4

addons:
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.cache
    - Godeps/_workspace

before_install:
  - mkdir -p $HOME/.cache/local
  - export LD_INSTALL_PREFIX=$HOME/.cache/local
  - export LD_LIBRARY_PATH=$LD_INSTALL_PREFIX/lib:$LD_LIBRARY_PATH
  - export LIBRARY_PATH=$LD_INSTALL_PREFIX/lib:$LIBRARY_PATH
  - export PKG_CONFIG_PATH=$LD_INSTALL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH
  - mkdir -p $LD_INSTALL_PREFIX/src
  - pushd $LD_INSTALL_PREFIX/src
  - $TRAVIS_BUILD_DIR/scripts/build-git-lib.sh git://github.com/jedisct1/libsodium.git
  - $TRAVIS_BUILD_DIR/scripts/build-git-lib.sh git://github.com/zeromq/libzmq.git
  - $TRAVIS_BUILD_DIR/scripts/build-git-lib.sh git://github.com/zeromq/czmq.git
  - popd
  - ./scripts/if-differ.sh Godeps/Godeps.json $HOME/.cache/Godeps.json rm -rf Godeps/_workspace

before_script:
  - psql -c 'CREATE DATABASE skygear_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d skygear_test
  - >
    go get golang.org/x/tools/cmd/stringer \
           golang.org/x/tools/cmd/cover \
           github.com/golang/lint/golint \
           github.com/smartystreets/goconvey/convey \
           github.com/smartystreets/assertions \
           github.com/rickmak/gocyclo \
           github.com/oursky/gogocyclo

script:
  - golint ./... | grep -v -f .golint.exclude
  - go generate ./...
  - gocyclo -skip-godeps -over 15 . | gogocyclo
  - go test -cover ./...

notifications:
  slack: oursky:PxqsclRADehuWEs51vpgxeUh
