# docker-compose.yml for Skygear
#
# If you need to override parts of this file, please create
# `docker-compose.override.yml` in the same directory of this file and
# specify overrided attributes.
# See also: https://docs.docker.com/compose/extends/
# (requires docker-compose 0.5 or above)

# The `*_data` are data volume containers used to keep persistent data.
# It is save to delete and recreate non-data-volume containers.

db_data:
  image: mdillon/postgis:9.4
  command: /bin/true

# The database container
db:
  image: mdillon/postgis:9.4
  volumes_from:
  - db_data
  ports:
  - "5432:5432"

redis_data:
  image: redis:3.0
  command: /bin/true

redis:
  image: redis:3.0
  volumes_from:
  - redis_data

app_data:
  image: oursky/skygear:latest
  command: /bin/true

# The Skygear container
app:
  image: oursky/skygear:latest
  ports:
  - "3000:3000" # Skygear API Endpoint (HTTP)
  - "5555:5555" # Skygear Plugin Endpoint (ZMQ)
  volumes_from:
  # Uncomment the following line to override the default configuration file.
  #- ./development.ini:/go/src/app/development.ini
  - app_data
  links:
  - db
  - redis
  command: skygear development.ini
  environment:
    # `db` in the following string should match the name of the database
    # container above.
    DATABASE_URL: postgresql://postgres:@db/postgres?sslmode=disable
    REDISTEST: redis://redis:6379
    DB_IMPL_NAME: pq
    API_KEY: changeme
    PGHOST: db
    PGUSER: postgres
    # GOMAXPROCS - The maximum number of Go threads for execution.
    # When unspecified, the default is the number of CPU available, which
    # is the recommended setting.
    #GOMAXPROCS: 1
