
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = [
  "golang.org/x/tools/cmd/stringer",
  "golang.org/x/tools/cmd/cover",
  "github.com/mitchellh/gox",
  "github.com/golang/mock/mockgen",
  "github.com/tinylib/msgp"
]

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "~3.1.0"

[[constraint]]
  name = "github.com/evalphobia/logrus_fluent"
  version = "0.4.0"

[[constraint]]
  name = "github.com/franela/goreq"
  revision = "b5b0f5eb2d16f20345cce0a544a75163579c0b00"

[[constraint]]
  name = "github.com/golang/mock"
  version = "~1.1.0"

[[constraint]]
  name = "github.com/jmoiron/sqlx"
  revision = "d9bd385d68c068f1fabb5057e3dedcbcbb039d0f"

[[constraint]]
  name = "github.com/joho/godotenv"
  revision = "4ed13390c0acd2ff4e371e64d8b97c8954138243"

[[constraint]]
  name = "github.com/lann/squirrel"
  revision = "e13dbacee404686afd0acf2d44b8d34869605e03"

[[constraint]]
  name = "github.com/lib/pq"
  revision = "8c6ee72f3e6bcb1542298dd5f76cb74af9742cec"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.1"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "~1.6.3"

[[constraint]]
  name = "github.com/twinj/uuid"
  revision = "b505f2cca343b7b21416b27b1f2ad88469800892"

[[constraint]]
  name = "golang.org/x/crypto"
  revision = "173ce04bfaf66c7bb0fa9d5c0bfd93e773909dbd"

[[constraint]]
  name = "github.com/nbutton23/zxcvbn-go"
  revision = "eafdab6b0663b4b528c35975c8b0e78be6e25261"

[[constraint]]
  name = "github.com/rifflock/lfshook"
  version = "2.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/kr/text"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/tinylib/msgp"
  version = "1.0.2"

[[constraint]]
  name = "github.com/go-gomail/gomail"
  version = "2.0.0"

[[constraint]]
  name = "github.com/flosch/pongo2"
  version = "3.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/sfreiberg/gotwilio"

[[constraint]]
  name = "github.com/njern/gonexmo"
  version = "2.0.0"

[[constraint]]
  name = "github.com/h2non/gock"
  version = "1.0.12"
