version: '1'
app_name: myapp
app_config:
  database_url: postgres://
user_config:
  api_key: apikey
  master_key: masterkey
deployment_routes:
- type: http-service
  path: /
  type_config:
    backend_url: http://localhost:9999
