api_version: 'v2.1'
app_id: myapp
app_name: myapp
database_config:
  database_url: postgres://postgres:@localhost:5432/postgres?sslmode=disable
  database_schema: app
  smtp:
    host: smtp.gmail.com
    port: 587
    login: your.gmail.account@gmail.com
    password: enable-2fa-and-use-app-password
app_config:
  api_version: 'v2.1'
  clients:
  - client_id: api_key
    client_name: Test App
    redirect_uris:
    - "http://localhost:9999/sso.html"
    grant_types:
    - authorization_code
    - refresh_token
  master_key: master_key
  asset:
    secret: assetsecret
  hook:
    secret: hooksecret
  welcome_email:
    enabled: true
  user_verification:
    login_id_keys:
    - key: email
    - key: phone
  auth:
    enable_api: true
    authentication_session:
      secret: authnsessionsecret
  sso:
    oauth:
      state_jwt_secret: statesecret
      providers:
      - type: google
        client_id: 'client_id'
        client_secret: 'client_secret'
  oidc:
    keys:
      - kid: key1
        public_key: |
          -----BEGIN PUBLIC KEY-----
          ...
          -----END PUBLIC KEY-----
        private_key: |
          -----BEGIN RSA PRIVATE KEY-----
          ...
          -----END RSA PRIVATE KEY-----
deployment_routes:
  - type: http-service
    path: /
    type_config:
      backend_url: 'http://localhost:9999'
# hooks:
# - event: "user_sync"
#   url: "http://localhost:9999/user_sync"
# 
# - event: "before_user_create"
#   url: "http://localhost:9999/before_user_create"
# - event: "after_user_create"
#   url: "http://localhost:9999/after_user_create"
# 
# - event: "before_user_update"
#   url: "http://localhost:9999/before_user_update"
# - event: "after_user_update"
#   url: "http://localhost:9999/after_user_update"
# 
# - event: "before_session_create"
#   url: "http://localhost:9999/before_session_create"
# - event: "after_session_create"
#   url: "http://localhost:9999/after_session_create"
# - event: "before_session_delete"
#   url: "http://localhost:9999/before_session_delete"
# - event: "after_session_delete"
#   url: "http://localhost:9999/after_session_delete"
# 
# - event: "before_identity_create"
#   url: "http://localhost:9999/before_identity_create"
# - event: "after_identity_create"
#   url: "http://localhost:9999/after_identity_create"
# - event: "before_identity_delete"
#   url: "http://localhost:9999/before_identity_delete"
# - event: "after_identity_delete"
#   url: "http://localhost:9999/after_identity_delete"
# 
# - event: "before_password_update"
#   url: "http://localhost:9999/before_password_update"
# - event: "after_password_udpate"
#   url: "http://localhost:9999/after_password_udpate"
